server:
    port: 9003
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8070/eureka/
spring:
    cloud:
        gateway:
            discovery.locator:
                enabled: true
                lowerCaseServiceId: true
            filter:
                - RemoveRequestHeader= Cookie,Set-Cookie
management:
    endpoints:
        web:
            exposure:
                include: "*"
